-- AUTO-GENERATED: Cleanup script for menu_items table
-- Generated by clean-menu-data.py
-- Items to remove: 545

-- Step 1: Delete kids menu items by name
DELETE FROM menu_items WHERE
  (restaurant_name = 'Arby''s' AND name = 'Chicken Tenders (2) (Kids Menu)') OR
  (restaurant_name = 'Clean Eatz' AND name = 'Turkey Burger (per patty)') OR
  (restaurant_name = 'Firehouse Subs' AND name = 'Kid''s Grilled Cheese') OR
  (restaurant_name = 'Firehouse Subs' AND name = 'Kid''s Ham Sub') OR
  (restaurant_name = 'Firehouse Subs' AND name = 'Kid''s Meatball') OR
  (restaurant_name = 'Firehouse Subs' AND name = 'Kid''s Roast Beef') OR
  (restaurant_name = 'Firehouse Subs' AND name = 'Kid''s Turkey Sub') OR
  (restaurant_name = 'PDQ' AND name = 'Kids Crispy Chicken Tenders') OR
  (restaurant_name = 'PDQ' AND name = 'Kids Grilled Chicken Tenders') OR
  (restaurant_name = 'PDQ' AND name = 'Kids Nuggets') OR
  (restaurant_name = 'Popeyes' AND name = 'Tender - Classic (Kids Meal)') OR
  (restaurant_name = 'Popeyes' AND name = 'Leg - Classic (Kids Meal)') OR
  (restaurant_name = 'Subway' AND name = 'Veggie Delite Kids Mini Sub') OR
  (restaurant_name = 'Subway' AND name = 'Black Forest Ham Kids Mini Sub') OR
  (restaurant_name = 'Subway' AND name = 'Oven Roasted Turkey Kids Mini Sub') OR
  (restaurant_name = 'Tropical Smoothie Cafe' AND name = 'Cheese ''Dilla') OR
  (restaurant_name = 'Tropical Smoothie Cafe' AND name = 'Turkey & Cheddar Wrap') OR
  (restaurant_name = 'True Food Kitchen' AND name = 'Chicken Teriyaki Bowl') OR
  (restaurant_name = 'True Food Kitchen' AND name = 'Kid''s Blueberry Pancake') OR
  (restaurant_name = 'True Food Kitchen' AND name = 'Grass-Fed Cheeseburger') OR
  (restaurant_name = 'Wendy''s' AND name = 'Kid''s Cheeseburger') OR
  (restaurant_name = 'Wendy''s' AND name = 'Kid''s Hamburger');

-- Step 2: Delete all items with calories <= 100
DELETE FROM menu_items
WHERE (macros->>'calories')::int <= 100;

-- Step 3: Verify remaining count
SELECT COUNT(*) as remaining_items FROM menu_items;
