/**
 * LLM Swap Fallback
 * Only invoked when ZERO swaps are generated by both the DB-backed engine
 * and the global swap library. Uses OpenAI to generate realistic restaurant
 * modification suggestions.
 *
 * RULE: Never fabricate nutrition values. Returns qualitative labels only.
 */

import { openai } from '@ai-sdk/openai';
import { generateObject } from 'ai';
import { z } from 'zod';

// ---------- Types ----------

export interface LLMSwapSuggestion {
    id: string;
    label: string;
    impactLabels: string[];
    details: string;
    estimatedDelta: {
        calories: number;
        protein: number;
        carbs: number;
        fats: number;
    };
    source: 'llm';
}

// ---------- Zod schema for structured LLM output ----------

const llmSwapSchema = z.object({
    swaps: z.array(
        z.object({
            label: z.string().describe('Short label for the modification, e.g. "Grilled instead of fried"'),
            impactLabels: z.array(z.string()).describe('Qualitative impact labels like "Reduce calories", "Higher protein"'),
            details: z.string().describe('Brief explanation of why this swap helps'),
            calories: z.number().describe('Estimated calorie change (negative = reduction)'),
            protein: z.number().describe('Estimated protein change in grams'),
            carbs: z.number().describe('Estimated carb change in grams'),
            fats: z.number().describe('Estimated fat change in grams'),
        })
    ).min(1).max(3),
});

// ---------- Public API ----------

/**
 * Generates swap suggestions using an LLM as a last resort.
 * Only call this when no swaps are available from the DB engine or global library.
 *
 * @param mealName - Name of the meal (e.g., "Classic Burger")
 * @param restaurantName - Restaurant name
 * @param mealMacros - The nutritional context of the meal
 * @param requiredCount - The number of swaps to generate
 * @returns Array of LLM-generated swap suggestions
 */
export async function generateLLMSwaps(
    mealName: string,
    restaurantName: string,
    mealMacros: { calories: number; protein: number; carbs: number; fats: number },
    requiredCount: number = 3
): Promise<LLMSwapSuggestion[]> {
    try {
        const { object } = await generateObject({
            model: openai('gpt-4o-mini'),
            schema: llmSwapSchema,
            prompt: `You are a restaurant nutrition advisor. Given this meal: "${mealName}" at "${restaurantName}", suggest ${requiredCount} realistic modifications that a customer could actually request when ordering to make it healthier.

MEAL MACROS: ${mealMacros.calories} cal, ${mealMacros.protein}g protein, ${mealMacros.carbs}g carbs, ${mealMacros.fats}g fat

Rules:
- Only suggest modifications that are realistic for a restaurant to accommodate.
- Estimate realistic macro changes (calories, protein, carbs, fats). Base your estimates on what this SPECIFIC meal likely contains. A 140 cal veggie burger doesn't have 300 cal of fries.
- Negative values = reduction, positive values = increase.
- A swap CANNOT reduce more calories/macros than the meal actually has.
- Focus on practical changes like cooking method, portion adjustments, ingredient swaps.
- Keep labels short and actionable.
- Impact labels should be one of: "Reduce calories", "Lower carbs", "Higher protein", "Reduce fat", "Lighter preparation", "Reduce sauce calories", "Smaller portion".
- Details should be 1 sentence explaining the benefit.`,
        });

        return object.swaps.map((swap, index) => ({
            id: `llm-swap-${index}-${Date.now()}`,
            label: swap.label,
            impactLabels: swap.impactLabels,
            details: swap.details,
            estimatedDelta: {
                calories: swap.calories,
                protein: swap.protein,
                carbs: swap.carbs,
                fats: swap.fats
            },
            source: 'llm' as const,
        }));
    } catch (error) {
        if (process.env.NODE_ENV === 'development') {
            console.error('[swap-llm-fallback] Error generating LLM swaps:', error);
        }
        return [];
    }
}

// ---------- LLM Macro Refinement (Phase 2, Option C) ----------

/**
 * Schema for batched macro refinement response.
 * One refined delta per swap label.
 */
const macroRefinementSchema = z.object({
    refinedDeltas: z.array(
        z.object({
            swapLabel: z.string().describe('Exact swap label from the input'),
            calories: z.number().describe('Estimated calorie change (negative = reduction)'),
            protein: z.number().describe('Estimated protein change in grams'),
            carbs: z.number().describe('Estimated carb change in grams'),
            fats: z.number().describe('Estimated fat change in grams'),
            reasoning: z.string().describe('One sentence explaining the estimate'),
        })
    ),
});

export interface RefinedMacroDelta {
    swapLabel: string;
    calories: number;
    protein: number;
    carbs: number;
    fats: number;
    reasoning: string;
}

/**
 * Batched LLM call to refine macro estimates for heuristic swaps.
 *
 * Sends all swap labels + meal context in ONE prompt.
 * Returns refined deltas, or null on failure (caller should fall back to clamped heuristic).
 *
 * Gated behind ENABLE_SWAP_LLM_MACROS env var.
 *
 * @param mealName        - e.g., "Veggie Burger"
 * @param restaurantName  - e.g., "Five Guys"
 * @param mealMacros      - actual meal macros {calories, protein, carbs, fats}
 * @param swapLabels      - array of swap labels to refine, e.g. ["Side salad instead of fries", "Light sauce"]
 * @returns Array of refined deltas matching the input swap labels, or null on failure
 */
export async function refineMacrosViaLLM(
    mealName: string,
    restaurantName: string,
    mealMacros: { calories: number; protein: number; carbs: number; fats: number },
    swapLabels: string[]
): Promise<RefinedMacroDelta[] | null> {
    // Guard: disabled by default unless explicitly enabled
    if (process.env.ENABLE_SWAP_LLM_MACROS !== 'true') {
        return null;
    }

    if (swapLabels.length === 0) return null;

    try {
        const { object } = await generateObject({
            model: openai('gpt-4o-mini'),
            schema: macroRefinementSchema,
            prompt: `You are a restaurant nutrition expert. Given this specific meal and its macros, estimate the realistic macro impact of each modification.

MEAL: "${mealName}" at "${restaurantName}"
CURRENT MACROS: ${mealMacros.calories} cal, ${mealMacros.protein}g protein, ${mealMacros.carbs}g carbs, ${mealMacros.fats}g fat

MODIFICATIONS TO ESTIMATE:
${swapLabels.map((label, i) => `${i + 1}. "${label}"`).join('\n')}

Rules:
- Base your estimates on what this SPECIFIC meal likely contains. A 140 cal veggie burger doesn't have 300 cal of fries.
- Negative values = reduction, positive values = increase
- A swap CANNOT reduce more calories than the meal actually has
- No single swap should change more than 40% of any macro
- Consider what components this specific meal realistically includes
- Be conservative — it's better to underestimate than overestimate
- Return one entry per swap label, matching the exact label text`,
        });

        return object.refinedDeltas.map((d) => ({
            swapLabel: d.swapLabel,
            calories: Math.round(d.calories),
            protein: Math.round(d.protein),
            carbs: Math.round(d.carbs),
            fats: Math.round(d.fats),
            reasoning: d.reasoning,
        }));
    } catch (error) {
        if (process.env.NODE_ENV === 'development') {
            console.error('[swap-llm-fallback] Error refining macros via LLM:', error);
        }
        return null; // Caller falls back to clamped heuristic deltas
    }
}
